// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using impulse_spending_tracker.Data;

#nullable disable

namespace impulse_spending_tracker.Migrations
{
    [DbContext(typeof(ImpulseSpendingDbContext))]
    [Migration("20260423182139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PurchaseTags", b =>
                {
                    b.Property<int>("PurchasesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PurchasesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PurchaseTags");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.BudgetPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscretionaryCategoryLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("EssentialCategoryLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<double>("ImpulseCapPercentage")
                        .HasColumnType("double");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MonthlyLimit")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("BudgetPlans");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AverageDeliveryDays")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsOnlineOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("BudgetPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Installments")
                        .HasColumnType("int");

                    b.Property<int>("MerchantId")
                        .HasColumnType("int");

                    b.Property<string>("MoodBeforePurchase")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NeedLevel")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SpendingSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("WishlistItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BudgetPlanId");

                    b.HasIndex("MerchantId");

                    b.HasIndex("SpendingSessionId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("WishlistItemId")
                        .IsUnique();

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.SpendingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CheckoutCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemsAddedToCart")
                        .HasColumnType("int");

                    b.Property<int>("ItemsViewed")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SessionBudget")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("SpendingSessions");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MonthlyNetIncome")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("RiskToleranceScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("DesiredPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsPurchased")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TargetPurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("PurchaseTags", b =>
                {
                    b.HasOne("impulse_spending_tracker.Models.Purchase", null)
                        .WithMany()
                        .HasForeignKey("PurchasesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("impulse_spending_tracker.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.BudgetPlan", b =>
                {
                    b.HasOne("impulse_spending_tracker.Models.UserProfile", "UserProfile")
                        .WithMany("BudgetPlans")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.Purchase", b =>
                {
                    b.HasOne("impulse_spending_tracker.Models.BudgetPlan", "BudgetPlan")
                        .WithMany("CoveredPurchases")
                        .HasForeignKey("BudgetPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("impulse_spending_tracker.Models.Merchant", "Merchant")
                        .WithMany("Purchases")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("impulse_spending_tracker.Models.SpendingSession", "SpendingSession")
                        .WithMany("Purchases")
                        .HasForeignKey("SpendingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("impulse_spending_tracker.Models.UserProfile", "UserProfile")
                        .WithMany("Purchases")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("impulse_spending_tracker.Models.WishlistItem", "WishlistItem")
                        .WithOne("ConvertedPurchase")
                        .HasForeignKey("impulse_spending_tracker.Models.Purchase", "WishlistItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BudgetPlan");

                    b.Navigation("Merchant");

                    b.Navigation("SpendingSession");

                    b.Navigation("UserProfile");

                    b.Navigation("WishlistItem");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.SpendingSession", b =>
                {
                    b.HasOne("impulse_spending_tracker.Models.UserProfile", "UserProfile")
                        .WithMany("Sessions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.WishlistItem", b =>
                {
                    b.HasOne("impulse_spending_tracker.Models.UserProfile", "UserProfile")
                        .WithMany("WishlistItems")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.BudgetPlan", b =>
                {
                    b.Navigation("CoveredPurchases");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.Merchant", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.SpendingSession", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.UserProfile", b =>
                {
                    b.Navigation("BudgetPlans");

                    b.Navigation("Purchases");

                    b.Navigation("Sessions");

                    b.Navigation("WishlistItems");
                });

            modelBuilder.Entity("impulse_spending_tracker.Models.WishlistItem", b =>
                {
                    b.Navigation("ConvertedPurchase");
                });
#pragma warning restore 612, 618
        }
    }
}
